### ISSUE TITLE
Generate packages containing the messages of well-known googleapis protos

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc-tools#9]
Packages need to be generated for each language supported by api-packager that contain the code generated from the well-known googleapis protos.

Rationale:
- [grpc-api-packager][] is used to create gRPC service packages from protos in the [googleapis][] project
- Some of the gRPC services depend on well-known photos
  - some well-known protos, e.g [empty.proto][] are defined in the [protobuf][] package and have copies in [googleapis][]
  - others, e.g. [operations.proto][] are exclusive to [googleapis][]
- It's possible to update [grpc-api-packager][] to include generated code for any well-known proto it depends on and include it in the generated package
- This leads to potential conflicts if two different generated libraries that depend on the same well-known proto are imported.
- This is not an issue in all generated libraries
  - e.g, its not an issue for the nodeJS generated libraries because of how the client constructor is generated dynamically using ProtoBuf.js
- It is an issue for most other packaged languages (ruby, python, php, c#, objective-c, go)
- In all these languages, the proposal is to
  - generate a package that contains generated messages for all the well-known protos in googleapis
  - make this a dependency of all packages whose services depend on well-known protos

Summary:
- these packages should also be generated by [grpc-api-packager][], probably with a different set of templates in the various language to reflect differences between these packages and actual service packages. 
- a candidate name for the package is `grpc-googleapis-messages`
- the package's version would be linked to the version of a release branch of the googleapis repo

[googleapis]: https://github.com/google/googleapis
[protobuf]: https://github.com/google/protobuf
[operations.proto]: https://github.com/google/googleapis/blob/master/google/longrunning/operations.proto
[empty.proto]: https://github.com/google/googleapis/blob/master/google/protobuf/empty.proto
[grpc-api-packager]: https://github.com/grpc/grpc-tools/blob/master/bin/grpc-api-packager

**Comment by tbetbetbe** [comment]
@wora, @jcanizales PTAL

**Comment by jcanizales** [comment]
> `grpc-googleapis-messages`

`common-messages` better? And there won't be anything grpc-specific about them, so what about something like `googleapis-common-proto-messages`?

**Comment by tbetbetbe** [comment]
>  what about something like googleapis-common-proto-messages
+1

**Comment by wora** [comment]
Because packages in googleapis will depend on well known types, it means they have to be built in compatible way. So we will have to use the packager tool on both side. As we discussed previously, we should use the naming convention grpc-google-protobuf-1.x.x, because the package name is google.protobuf.

NOTE: well known types are from protobuf. it was temporarily included in googleapis because of build and package issues. Once we know how to build protobuf, grpc, googleapis in compatible way, google.protobuf package should only be in protobuf.

**Comment by ejona86** [comment]
I thought the protobuf runtime libraries were going to include the compiled generated code and original .protos for the builtin types. This is already being done for Java, at the very least.

**Comment by jcanizales** [comment]
The common `annotations.proto` and `http.proto` under `googleapis/google/api` aren't part of the WKTs protobuf distributes, though.

And at least a week ago, running protoc for ObjC on a clone of this repo required `descriptor.proto` to be present under `google/protobuf`. @TeBoring knows better whether that's part of the plan, and whether it has changed.

**Comment by ejona86** [comment]
I wouldn't expect annotations and http to be needed by any services. I don't mind packaging them, but it didn't seem what this was about, especially since "empty.proto" was mentioned above. I thought it would be things like empty.proto and descriptor.proto, which it seemed the place was to include in protobuf itself.

**Comment by jcanizales** [comment]
> I wouldn't expect annotations and http to be needed by any services.

Not directly, but service code that's generated with descriptors needs the generated code for the two. At least ObjC does.

**Comment by ejona86** [comment]
Ah, I see, service protos may import annotations and http and use them, in which case they become needed.

**Comment by tbetbetbe** [comment]
@vsubramani PTAL

**Comment by pcostell** [comment]
@tbetbetbe, any progress on this?

**Comment by tbetbetbe** [comment]
Not yet, sorry.  ETA end-of-this week.  I've been focused on the gRPC beta
release, which should be ready today.

On 3 September 2015 at 15:31, Patrick Costello <notifications@github.com>
wrote:

> @tbetbetbe <https://github.com/tbetbetbe>, any progress on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc-tools/issues/9#issuecomment-137591249>.
>



-- 
This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else (it may
contain confidential or privileged information), please erase all copies of
it, including all attachments, and please let the sender know it went to
the wrong person. Thanks.

**Comment by tbetbetbe** [comment]
@pcostell: sorry the delay, this should be ready later this week.

**Comment by tbetbetbe** [comment]
FYI: @bcy1028
